package com.articool.groups.service;

import java.util.List;

import com.articool.groups.domain.Group;
import com.articool.utility.GoogleDataStoreHelper;
import static com.googlecode.objectify.ObjectifyService.ofy;

public class GroupServiceImpl implements GroupService {
	
	private GoogleDataStoreHelper googleDataStoreHelper = new GoogleDataStoreHelper();
	
	@Override
	public Group set(Group group) {
		ofy().save().entity(group).now();
		assert group.id != null;    // id was autogenerated
		googleDataStoreHelper.indexDataStore(Group.class, group.id);
		
		return group;
	}

	@Override
	public List<Group> get() {
		List<Group> groups = ofy().load().type(Group.class).list();
		return groups;
	}

	@Override
	public void delete(Long id) {
		ofy().delete().type(Group.class).id(id).now();
		googleDataStoreHelper.indexDataStore(Group.class, id);
	}

	@Override
	public void update(Group reqGroup) {
		ofy().save().entity(reqGroup).now();
		googleDataStoreHelper.indexDataStore(Group.class, reqGroup.getId());
		
	}

	@Override
	public Group getOneGroupById(Long id) {
		
		Group  group =  ofy().load().type(Group.class).filter("id", id).first().get();
		return group;
		
	}

}